# .github/workflows/update-videos.yml
name: Update Mizo Leakout Videos

on:
  workflow_dispatch:
    inputs:
      videos_per_category:
        description: 'Number of videos per category'
        required: true
        default: '150'
        type: string
  schedule:
    # Update videos every Sunday at midnight
    - cron: '0 0 * * 0'

jobs:
  update-videos:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Generate new video database
      run: |
        echo "🎬 Generating videos for Mizo Leakout..."
        python generate_videos.py
        
    - name: Commit and push new videos
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Mizo Leakout Bot"
        git add videos.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🎬 Update Mizo Leakout video database - $(date '+%Y-%m-%d %H:%M')"
          git push
        fi
